[project]
name = "meraid-gantts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openpyxl",    # For reading/writing Excel files
    "pytest",      # For running tests
]
